package com.borsibaar.exception;

public enum FaultReason {

    UNAUTHORIZED,
    FORBIDDEN,
    ADMIN_REQUIRED,

    NOT_FOUND,
    RESOURCE_DELETED,
    DUPLICATE_RESOURCE,

    VALIDATION_ERROR,
    CONSTRAINT_VIOLATION,

    INSUFFICIENT_STOCK,
    ORGANIZATION_REQUIRED,
    ORGANIZATION_MISMATCH,

    BAD_REQUEST,
    INTERNAL_SERVER_ERROR,
    DATA_INTEGRITY_VIOLATION
}
